networks:
  nx-microray-network:
    driver: bridge

volumes:
  nx-microray-mongodb-data:
    driver: local
  nx-microray-app-node-modules:
    driver: local
  nx-microray-app-next-cache:
    driver: local

services:
  nx-microray-mongodb:
    image: cdray527/nx-microray-mongodb:latest
    container_name: nx-microray-mongodb
    build:
      context: ./mongo/
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - nx-microray-mongodb-data:/data/db
    networks:
      - nx-microray-network

  nx-microray-mongoexpress:
    image: mongo-express
    container_name: nx-microray-mongoexpress
    ports:
      - "8088:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: nx-microray-mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      nx-microray-mongodb:
        condition: service_healthy
    networks:
      - nx-microray-network

  nx-microray-app-host:
    image: cdray527/nx-microray-app:dev
    container_name: nx-microray-app-host
    build:
      context: ../nx-microray-app/
      dockerfile: Dockerfile
    volumes:
      - ../nx-microray-app:/usr/src/app
      - nx-microray-app-node-modules:/usr/src/app/node_modules
      - nx-microray-app-next-cache:/usr/src/app/.next
    command: ["nx", "run", "host:serve:development"]
    ports:
      - "4000:4000"
    networks:
      - nx-microray-network

  nx-microray-app-store:
    image: cdray527/nx-microray-app:dev
    container_name: nx-microray-app-store
    build:
      context: ../nx-microray-app/
      dockerfile: Dockerfile
    volumes:
      - ../nx-microray-app:/usr/src/app
      - nx-microray-app-node-modules:/usr/src/app/node_modules
      - nx-microray-app-next-cache:/usr/src/app/.next
    command: ["nx", "run", "store:serve:development"]
    depends_on:
      - nx-microray-app-host
    ports:
      - "4100:4100"
    networks:
      - nx-microray-network

  nx-microray-app-product:
    image: cdray527/nx-microray-app:dev
    container_name: nx-microray-app-product
    build:
      context: ../nx-microray-app/
      dockerfile: Dockerfile
    volumes:
      - ../nx-microray-app:/usr/src/app
      - nx-microray-app-node-modules:/usr/src/app/node_modules
      - nx-microray-app-next-cache:/usr/src/app/.next
    command: ["nx", "run", "product:serve:development"]
    depends_on:
      - nx-microray-app-host
    ports:
      - "4200:4200"
    networks:
      - nx-microray-network

  nx-microray-app-checkout:
    image: cdray527/nx-microray-app:dev
    container_name: nx-microray-app-checkout
    build:
      context: ../nx-microray-app/
      dockerfile: Dockerfile
    volumes:
      - ../nx-microray-app:/usr/src/app
      - nx-microray-app-node-modules:/usr/src/app/node_modules
      - nx-microray-app-next-cache:/usr/src/app/.next
    command: ["nx", "run", "checkout:serve:development"]
    depends_on:
      - nx-microray-app-host
    ports:
      - "4300:4300"
    networks:
      - nx-microray-network

  nx-microray-storybook:
    image: cdray527/nx-microray-app:dev
    container_name: nx-microray-storybook
    command: ["nx", "storybook", "design-system"]
    volumes:
      - ../nx-microray-app:/usr/src/app
      - nx-microray-app-node-modules:/usr/src/app/node_modules
      - nx-microray-app-next-cache:/usr/src/app/.next
    depends_on:
      - nx-microray-app-host
    ports:
      - "6006:6006"
    networks:
      - nx-microray-network

  nx-microray-api-product:
    image: cdray527/nx-microray-api-product:dev
    build:
      context: ../nx-microray-api/product
      dockerfile: Dockerfile
    container_name: nx-microray-api-product
    depends_on:
      - nx-microray-mongodb
    environment:
      MONGO_URI: "mongodb://nx-microray-mongodb:27017"
      PORT: "5200"
    volumes:
      - ../nx-microray-api/product:/usr/src/api
    command: ["go", "run", "product.go"]
    ports:
      - "5200:5200"
    networks:
      - nx-microray-network
