networks:
  nx-microray-network:
    driver: bridge

volumes:
  nx-microray-mongodb-data:
    driver: local

services:
  nx-microray-nginx:
    image: nginx:latest
    container_name: nx-microray-nginx
    ports:
      - "80:80"
      # - "443:443" # enable HTTPS connection
    depends_on:
      - nx-microray-api-product
      - nx-microray-mongodb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./cert/:/etc/nginx/cert/
    networks:
      - nx-microray-network

  nx-microray-mongodb:
    image: mongo
    container_name: nx-microray-mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: mongod --quiet
    volumes:
      - nx-microray-mongodb-data:/data/db
    networks:
      - nx-microray-network

  nx-microray-app-host:
    image: cdray527/nx-microray-app:prod
    container_name: nx-microray-app-host
    command: ["npx", "next", "start", "dist/apps/host", "-p 4000"]
    build:
      context: ../nx-microray-app/
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000
    networks:
      - nx-microray-network

  nx-microray-app-store:
    image: cdray527/nx-microray-app:prod
    container_name: nx-microray-app-store
    command: ["npx", "next", "start", "dist/apps/store", "-p 4100"]
    depends_on:
      - nx-microray-app-host
    ports:
      - 4100:4100
    networks:
      - nx-microray-network

  nx-microray-app-product:
    image: cdray527/nx-microray-app:prod
    container_name: nx-microray-app-product
    command: ["npx", "next", "start", "dist/apps/product", "-p 4200"]
    depends_on:
      - nx-microray-app-host
    ports:
      - 4200:4200
    networks:
      - nx-microray-network

  nx-microray-app-checkout:
    image: cdray527/nx-microray-app:prod
    container_name: nx-microray-app-checkout
    command: ["npx", "next", "start", "dist/apps/checkout", "-p 4300"]
    depends_on:
      - nx-microray-app-host
    ports:
      - 4300:4300
    networks:
      - nx-microray-network

  nx-microray-api-product:
    image: cdray527/nx-microray-api-product:latest
    build:
      context: ../nx-microray-api/product
      dockerfile: Dockerfile.prod
    container_name: nx-microray-api-product
    depends_on:
      - nx-microray-mongodb
    environment:
      MONGO_URI: "mongodb://nx-microray-mongodb:27017"
    volumes:
      - ../nx-microray-api/product:/usr/src/api
    # command: "sleep 5000"
    command: ["./product"]
    # command: ["go", "run", "product.go"]
    ports:
      - "5200:5200"
    networks:
      - nx-microray-network
