networks:
  nx-microray-network:
    driver: bridge

volumes:
  nx-microray-mongodb-data:
    driver: local

services:
  nx-microray-nginx:
    image: nginx:latest
    container_name: nx-microray-nginx
    ports:
      - "80:80"
      # - "443:443" # enable HTTPS connection
    depends_on:
      - nx-microray-app
      - nx-microray-api-product
      - nx-microray-mongodb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./cert/:/etc/nginx/cert/
    networks:
      - nx-microray-network

  nx-microray-mongodb:
    image: cdray527/nx-microray-mongodb:latest
    container_name: nx-microray-mongodb
    build:
      context: ./mongo/
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - nx-microray-mongodb-data:/data/db
    networks:
      - nx-microray-network

  nx-microray-mongoexpress:
    image: mongo-express
    container_name: nx-microray-mongoexpress
    ports:
      - "8088:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: nx-microray-mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      nx-microray-mongodb:
        condition: service_healthy
    networks:
      - nx-microray-network

  nx-microray-app:
    image: cdray527/nx-microray-app:dev
    container_name: nx-microray-app
    build:
      context: ../nx-microray-app/
      dockerfile: Dockerfile
    volumes:
      - ../nx-microray-app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    command: ["nx", "run-many", "--target=serve", "--all"]
    ports:
      - "4000:4000"
      - "4100:4100"
      - "4200:4200"
      - "4300:4300"
    networks:
      - nx-microray-network

  nx-microray-api-product:
    image: cdray527/nx-microray-api-product:dev
    build:
      context: ../nx-microray-api/product
      dockerfile: Dockerfile
    container_name: nx-microray-api-product
    depends_on:
      - nx-microray-mongodb
    environment:
      MONGO_URI: "mongodb://nx-microray-mongodb:27017"
    volumes:
      - ../nx-microray-api/product:/usr/src/api
    command: ["go", "run", "product.go"]
    ports:
      - "5200:5200"
    networks:
      - nx-microray-network
