FROM mongo:6.0

# Install MongoDB tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gnupg2 \
    curl && \
    echo "deb http://repo.mongodb.org/apt/debian stretch/multiverse amd64 Packages" > /etc/apt/sources.list.d/mongodb-org-6.0.list && \
    curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y mongo-tools && \
    rm -rf /var/lib/apt/lists/*